### ISSUE TITLE
Results update

### ISSUE THREAD

**Issue by jinshijian** [jinshijian/GlobalC#1]
After our meeting, I discussed with Alexey how to do this using boosting, and have got some results.

* Bottom-up approach to estimate GPP, medium, and 95% CI turns out to be (100, 147, 210), the mean is very close to the estimate by NIRv (Grayson Basgley 2019, you mentioned in the Twitter)! The blue histogram and CI (106,128,151) are from reported GPP in the publication.
![image](https://user-images.githubusercontent.com/13302161/60046272-ec949f00-9694-11e9-835d-c6e40c212155.png) 

* Top-down approach to estimate RS: medium and 95% CI turns out to be (57, 75, 97). The blue histogram and CI (72,84,94) are from reported GPP in the publication.
![image](https://user-images.githubusercontent.com/13302161/60046282-f4ecda00-9694-11e9-9ad1-85d83e9dd246.png)

**Comment by bpbond** [comment]
Again, sweet! Can you push up latest code to repo please?

**Comment by jinshijian** [comment]
## Potential analysis to improve the results:
* Froot, RC, and Ra-to-GPP ratio in some ecosystem have a very small sample size (see figures below).
* Suggestion from Alexey: if CMIP5 have those results, we could use that as a prior distribution, and based on the observations we have and using a Bayesian approach to have artificial samples.
* We can also search papers and see whether we can find more data.
* Other suggestions from Alexey: instead weight by ecosystem area, try weight by above ground biomass, by above ground carbon stock and below ground carbon stock.

![image](https://user-images.githubusercontent.com/13302161/60597200-8553aa80-9d78-11e9-9cf3-12a934756bf8.png)
![image](https://user-images.githubusercontent.com/13302161/60597259-9e5c5b80-9d78-11e9-9f15-474983648c10.png)
![image](https://user-images.githubusercontent.com/13302161/60597302-afa56800-9d78-11e9-85de-fdcd4275dc31.png)

**Comment by jinshijian** [comment]
* If only ecosystems with more than 40 observations were considered (for RC, Froot, and Ra/GPP), the results showed even less probability of current GPP and Rs is, please see the below figures. The project has been updated in Github, and the markdown file is commended for clarity. Thanks
![image](https://user-images.githubusercontent.com/13302161/60985965-73d84880-a30c-11e9-8990-e7100ce79e49.png)
![image](https://user-images.githubusercontent.com/13302161/60985984-7f2b7400-a30c-11e9-86e7-e5973f1e30bd.png)
