### ISSUE TITLE
GlobalGPP_Sum.csv values need to be carefully checked with consistent criteria

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#19]
All of these values are included in `GlobalGPP_Sum.csv`, including data-driven ones like MTE and MODIS but also pure model outputs like JULES and ORCHIDEE. What's the criterion here? If we're including the latter, why not include model outputs for Rs as well? 

Should we remove pure model outputs from `GlobalGPP_Sum.csv`? (I kind of think so?)

**Comment by bpbond** [comment]
Also the MODIS and MTE values appear at least twice in `GlobalGPP_Sum.csv`, from Chen et al. (2017) and Anav et al. (2015).

The Raddatz et al. (2007) entries seem to be using the **2100** values from that study's Figure 7. It's also a pure modeling result, so same question above applies.

**Comment by jinshijian** [comment]
GPP checked and updated.
