### ISSUE TITLE
Write Access

### ISSUE THREAD

**Issue by kdorheim** [jinshijian/GlobalC#20]
Hi @jinshijian I am working on the cmip6 data analysis and was wondering if you could change my access for this repo? I would like to be able to push my branch but I get the following error message 
```
we36668:GlobalC dorh012$ git push --set-upstream origin krd/cmip6
remote: Permission to jinshijian/GlobalC.git denied to kdorheim.
fatal: unable to access 'https://github.com/jinshijian/GlobalC.git/': The requested URL returned error: 403
```

Which I _think_ has to do with my permission access.

**Comment by bpbond** [comment]
I just checked and can't change this.

**Comment by jinshijian** [comment]
I invited you in the repo.

**Comment by kdorheim** [comment]
Curious it looks like I am still having some issues pushing the cmip processing scripts to the repo. It looks like I still don't have access. 
```
we36668:GlobalC dorh012$ git push --set-upstream origin krd/cmip6
remote: Permission to jinshijian/GlobalC.git denied to kdorheim.
fatal: unable to access 'https://github.com/jinshijian/GlobalC.git/': The requested URL returned error: 403
```

**Comment by jinshijian** [comment]
Hello Kalyn,

I see you already are one of the collaborators, I don't know what causes
the problem.
Are you create a branch and push that to the branch or do you directly push
to the master?
I am not good at github, if this problem still exists, Ben or Alexey may
can help.

Thanks,
Jinshi

**Comment by kdorheim** [comment]
Hi @jinshijian this has been taken care of and I have been able to push my commits to the `krd/cmip6` branch. Thanks for following up!
