### ISSUE TITLE
Check we have Badgley 2019 NIRv GPP

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#22]

**Comment by bpbond** [comment]
Also, from Grayson Badgley: Norton et al. paper on inverting Bethy -> gets GPP of 160+ https://www.biogeosciences.net/16/3069/2019/bg-16-3069-2019.html

**Comment by bpbond** [comment]
NIRv and SIF both have soil contamination in the signal

**Comment by bpbond** [comment]
Jen Johnson: turnover, yes, but also growing or shrinking biosphere / sink - trend

**Comment by bpbond** [comment]
E.g. a high-value sink might be less robust than a low-value sink...

**Comment by jinshijian** [comment]
GPP (167+-5) from Norton et al. (2019) paper added.
