### ISSUE TITLE
Issues in supplementary tables

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#45]
I've gone through the SI tables and put everything into the Paperpile/Docs reference system. A made some notes along the way–see Google Doc–there may be some problems with duplicated and out-of-date numbers. We can discuss further.

**Comment by jinshijian** [comment]
That looks great, thanks! I have to learn how to use Pipeline to manage citations.
Some duplicates removed, old citations replaced by the new paper and data now.

**Comment by bpbond** [comment]
Great, thanks.
