### ISSUE TITLE
Script should output the lon/lat values used in Figure 3

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#50]
Needed by @kdorheim for #24
 
@jinshijian I'm assigning you but I can also take this on if you're short on time. Thanks!

**Comment by jinshijian** [comment]
Will do it later

**Comment by jinshijian** [comment]
Hello @kdorheim, I have updated the repo, if you go to the bottom of "Topdown_GlobalRs.Rmd" file, I created a trunk to get the sites' lat and lon information from SRDB and Fluxnet with Rs-to-GPP ratio. 
I also attached the code below.
Thanks, Jinshi

srdb_v4 %>% 
  filter(!is.na(GPP), !is.na(Rs_annual), Ecosystem_state != "Managed") %>% 
  select(Rs = Rs_annual, GPP, Biome, Latitude, Longitude, Ecosystem_type) %>% 
  mutate(Biome = as.character(Biome), Ecosystem_type = as.character(Ecosystem_type)) -> RsGPP_srdb


read.csv("data/site-data-temp/srdb_filtered.csv", stringsAsFactors = FALSE) %>% 
  select(Biome, Ecosystem_type, FLUXNET_SITE_ID, Latitude, Longitude, GPP = gpp_fluxnet, Rs = Rs_annual) %>% 
  filter(!is.na(GPP), !is.na(Rs)) ->
  RsGPP_fluxnet

**Comment by bpbond** [comment]
Formatting @jinshijian 's comment to make it prettier 😄

**Comment by jinshijian** [comment]
Thank you @bpbond

**Comment by bpbond** [comment]
I think can close this?

**Comment by kdorheim** [comment]
@jinshijian and/or @bpbond what are the units on the GPP and Rs data here?

**Comment by bpbond** [comment]
Site-specific values are in gC/m2/yr.
