### ISSUE TITLE
What are most important variables for sensitivity?

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#53]
From meeting with @jinshijian and @abigailsnyder

Easy first pass is to re-run bootstrap a number of times, fixing each parameter (i.e. GPP, and each partitioning assumption for the GPP->Rs case) in turn. Quantify resulting µ and sigma, move on to next one, and summarize visually or in a table. This ignores higher-order interactions but still defensible given that this is not primary focus on analysis.

Sensitivity ≠ uncertainty!

**Comment by bpbond** [comment]
Supersedes #13

**Comment by jinshijian** [comment]
Hello @bpbond, I have updated the repo, with DOC and BVOCs components combined into the partition method. Currently, I do not have anything else to update, you can go-ahead pull the repo now. Thanks

**Comment by bpbond** [comment]
Thanks! I will tackle this on the weekend.
