### ISSUE TITLE
Data files need better documentation

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#56]
I'd suggest each file should start with a header that describes its contents and provides metadata for all fields. In addition, the `data/` folder should have a README file that provides a one-line summary for each file.

**Comment by bpbond** [comment]
For example, `GlobalRs.csv` starts like this currently:

```
ID,Pub_year,Period,Rs,SD,IncreaseRate,Rs_Reference,Rh,Ra,URL,
1,1977,1977,75,,,Schlesinger (1977),,,https://www.annualreviews.org/doi/pdf/10.1146/annurev.es.08.110177.000411,
2,1992,1962-1992,68,,,Raich (1992),,,https://onlinelibrary.wiley.com/doi/abs/10.1034/j.1600-0889.1992.t01-1-00001.x,
```

Instead, it would be clearer to have:

```
# Global soil respiration (Rs) estimates
# Columns include ID number (not used), publication year, period (year range of estimate), ...
ID,Pub_year,Period,Rs,SD,IncreaseRate,Rs_Reference,Rh,Ra,URL,
1,1977,1977,75,,,Schlesinger (1977),,,https://www.annualreviews.org/doi/pdf/10.1146/annurev.es.08.110177.000411,
2,1992,1962-1992,68,,,Raich (1992),,,https://onlinelibrary.wiley.com/doi/abs/10.1034/j.1600-0889.1992.t01-1-00001.x,
```

Then the only other thing needed I think would be to change line 101 in the RMarkdown file to
```R
read_file <- function(x) read.csv(file.path(DATA_DIR, x), comment.char = "#", stringsAsFactors = FALSE)
```

**Comment by jinshijian** [comment]
I agreed that it's very helpful to start with a title.
So, in the GlobalRs.csv file, I insert two rows at the beginning, and put:
# Global soil respiration (Rs) estimates
# Columns include ID number (not used), publication year, period (year range of estimate), ...
in these two columns, right? And do the same thing for other files if necessary?

Thanks,
Jinshi

**Comment by bpbond** [comment]
Right, but no single quote at the beginning. Here, I'll make a PR with an example.

**Comment by jinshijian** [comment]
Ok, I got it, thank you.

**Comment by jinshijian** [comment]
Hello Ben, I have added a header for all the files except the GlobalGPP_sum.csv file, because I got an error if I do so when reading the data to R.

**Comment by bpbond** [comment]
For full documentation, this was in #58 right.

Hmm, a header in `GlobalGPP_Sum.csv` works fine for me; see 4a36892.
