### ISSUE TITLE
CUE approach

### ISSUE THREAD

**Issue by jinshijian** [jinshijian/GlobalC#59]
## Now NPP is a big uncertainty source

__Another approach__
Using CUE approach by Konings (2019)

__Ben__
My guess is that CUE will just wrap up the NPP uncertainty into a new CUE uncertainty. I'd suggest opening a GitHub issue to track this idea, and we can discuss it next week?

**Comment by jinshijian** [comment]
Another point is currently both top-down approach and bottom-up approaches depend on NPP (see figure S1), so they are not independent?

**Comment by bpbond** [comment]
But we're not asserting that they _are_ independent, are we?

**Comment by jinshijian** [comment]
Right, I mean both approaches depend on NPP inputs. But I agree, we don't want to deal with it for now.
