### ISSUE TITLE
Another GPP study

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#6]
Stocker et al. (2019), https://www.creaf.uab.es/global-ecology/Pdfs_UEG/2019%20NatGeosc.pdf

Looks like they estimate ~130 Pg C/yr.

**Comment by bpbond** [comment]
Also: https://doi.org/10.5194/bg-2019-368

This looks like a great discussion point–scaling uncertainties. 

"In conclusion, global FLUXCOM GPP estimates are within the currently most plausible 110-150 PgC yr-1 range."

**Comment by jinshijian** [comment]
Values from these two papers added.
